import type { Metadata } from 'next';
import './globals.css';
import { google_sans } from './shared/font';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${google_sans.className}`}>{children}</body>
    </html>
  );
}
