import type { Metadata } from 'next';
import './globals.css';
import { grotesk } from './_module/shared/font';
import DFIHeader from './_module/components/common/DFIheader';
import DFIFooter from './_module/components/common/DFIfooter';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${grotesk.className}`}>
        <DFIHeader />
        {children}
        <DFIFooter />
      </body>
    </html>
  );
}
