import { IsString, IsNotEmpty } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class VerifyPaymentDto {
  @ApiProperty({
    description:
      'Unique payment reference generated by the payment gateway to identify the transaction',
    example: 'pay_1234567890abcdef',
  })
  @IsString()
  @IsNotEmpty()
  reference: string;
}
